name: Uber CI
on:
  pull_request:
    branches: [master]
    paths:
      - "uber/**"

jobs:
  flutter_test:
    name: Test client on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
        working-directory: ./uber
      - run: flutter analyze
        working-directory: ./uber
      - run: flutter test
        working-directory: ./uber

  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
        working-directory: ./uber
      - run: rm Podfile.lock
        working-directory: ./uber/ios
      - run: pod repo update
        working-directory: ./uber/ios
      - run: flutter clean
        working-directory: ./uber
      - run: flutter build ios --release --no-codesign
        working-directory: ./uber

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
        working-directory: ./uber
      - run: flutter clean
        working-directory: ./uber
      - run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
        env:
          SIGNING_KEY: ${{ secrets.ANDROID_SIGNING_KEY }}
        working-directory: ./uber
      - run: flutter build appbundle --release
        env:
          KEY_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEY_PATH: key.jks
        working-directory: ./uber
